### ISSUE TITLE
send.mail errors out with Rscript.exe

### ISSUE THREAD

**Issue by smzyij** [rpremraj/mailR#7]
I can run send.mail() successfully in R x64, but it errors out when I run it from command line x64\Rscript.exe.

Here is the code:
library(mailR)
send.mail(from = "xxxxxx@gmail.com",
          to = "xxxx@gmail.com",
          subject = "from Rscript",
          body = "As the title.",
          smtp = list(host.name = "smtp.gmail.com", port = 465, user.name = "xxxxxx", passwd = "xxxxxxxx", ssl = TRUE),
          authenticate = TRUE,
          send = TRUE)

Here is the error message from Rscript:
Error in email$setCharset : could not find function "loadMethod"
Calls: send.mail -> .resolveEncoding -> $
Execution halted

**Comment by santhoshdaivajna** [comment]
I am getting the same error mentioned above.

Error in email$setCharset : could not find function "loadMethod"
Calls: exitReport -> mail -> send.mail -> .resolveEncoding -> $
Execution halted

so as mentioned by @smzyij  I loaded the rJava library explicitly as below

library("rJava")
library("mailR")

now I get this error 

Loading required package: methods
Error in ls(envir = envir, all.names = private) :
  invalid 'envir' argument
Calls: exitReport ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
Execution halted

**Comment by rpremraj** [comment]
Can you use mailR successfully from the R environment?

Would be helpful if you could set the debug flag to True in send.mail() and share the output.

**Comment by santhoshdaivajna** [comment]
I enabled debug and ran the script.  There was a email address not verified exception. I verified it in Amazon SES and ran the program again. It's working now.

The debug log was as below
----------------------------------------------------------------------------------
RSET
250 Ok
DEBUG SMTP: MessagingException while sending, THROW:
com.sun.mail.smtp.SMTPSendFailedException: 554 Message rejected: Email address i                                                                                        s not verified.

        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2                                                                                        202)
        at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1980)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1197)
        at javax.mail.Transport.send0(Transport.java:254)
        at javax.mail.Transport.send(Transport.java:124)
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1400)
        at org.apache.commons.mail.Email.send(Email.java:1437)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.                                                                                        java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                        sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at RJavaTools.invokeMethod(RJavaTools.java:386)
QUIT
221 Bye
Error in ls(envir = envir, all.names = private) :
  invalid 'envir' argument
Calls: exitReport ... <Anonymous> -> .jrcall -> .jcall -> .jcheck -> .Call
Execution halted

**Comment by rpremraj** [comment]
Good to hear.

**Comment by rsaporta** [comment]
Hi, I am having the same issue running from a CENTOS machine. 

A command executes without fail from R, however fails if I use `Rscript -e '...'`

The problem is resolved by calling `library(rJava)` explicitly. However, I wonder if this is not a namespace issue?
